Repository AY2021S1-CS2113T-W11-2/tp, pull requests merged in 2020-11, with the labels that each got.

#119 Fix typo on the error message
  src/main/java/seedu/trippie/command/AddPlaceCommand.java
Labels: Priority.Low, severity.Low

#117 Ivander - edit/delete trip command
  src/main/java/seedu/trippie/Parser.java
  src/main/java/seedu/trippie/Storage.java
  src/main/java/seedu/trippie/Trippie.java
  src/main/java/seedu/trippie/command/DeleteTripCommand.java
  src/main/java/seedu/trippie/command/EditTripCommand.java
  src/main/java/seedu/trippie/command/NewTripCommand.java
  src/main/java/seedu/trippie/data/Trip.java
  src/main/java/seedu/trippie/data/TrippieData.java
  src/test/java/seedu/trippie/data/TrippieDataTest.java
  text-ui-test/EXPECTED.TXT
Labels: Priority.High, severity.Medium, type.Enhancement

#139 Fix edit trip
  docs/UserGuide.md
  docs/team/ivanderjmw.md
  src/main/java/seedu/trippie/Storage.java
  src/main/java/seedu/trippie/command/DeleteTripCommand.java
  src/main/java/seedu/trippie/command/EditTripCommand.java
  src/main/java/seedu/trippie/command/LoadTripCommand.java
  src/main/java/seedu/trippie/command/NewTripCommand.java
  src/main/java/seedu/trippie/data/Trip.java
  src/main/java/seedu/trippie/data/TrippieData.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: Priority.High, severity.High

#140 Add PPP and mock Trippie files
  docs/team/tengkianen.md
  trippie_data_mock/Hong Kong.txt
  trippie_data_mock/Tokyo.txt
  trippie_data_mock/United Kingdom.txt
  trippie_data_mock/trippie.txt
Labels: Priority.Medium, severity.Low

#141 Ivander - Add Uml diagrams
  docs/DeveloperGuide.md
  docs/diagrams/CommandExecutionSequence.puml
  docs/diagrams/GetPlace.puml
  docs/diagrams/ParseAndCheckCommand.puml
  docs/diagrams/ParseCommand.puml
  docs/diagrams/exports/CommandExecutionSequence.png
  docs/diagrams/exports/GetPlace.png
  docs/diagrams/exports/ParseAndCheckCommand.png
  docs/diagrams/exports/ParseCommand.png
  src/main/java/seedu/trippie/Trippie.java
Labels: Priority.High, severity.Low, type.Enhancement

#155 edit print statement
  src/main/java/seedu/trippie/Parser.java
  src/main/java/seedu/trippie/command/AddExpenseCommand.java
Labels: Priority.Low, severity.Medium, type.Bug
